# Generated by Django 2.1.5 on 2019-01-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0002_auto_20190121_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Select the book autor(s)', to='booklib.Author'),
        ),
    ]
